version: "3.8"

services:
  mongodb:
    image: mongo:5.0.8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_CONTAINER_PORT
    volumes:
      - db:/data/db
    networks:
      - network
  app:
    # build: .
    image: luisfelipe998/docker-k8s:0.0.1
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_CONTAINER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_CONTAINER_PORT
      - PORT=$APP_CONTAINER_PORT
    networks:
      - network
    labels:
      kompose.service.type: LoadBalancer
      kompose.service.external-traffic-policy: local

volumes:
  db:

networks:
  network:
    driver: bridge
