apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yml -o ./k8s
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yml -o ./k8s
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-kubernetes-arq-com-2-network: "true"
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: APP_CONTAINER_PORT
              value: "8080"
            - name: APP_LOCAL_PORT
              value: "8080"
            - name: MONGODB_CONTAINER_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: users
            - name: MONGODB_LOCAL_PORT
              value: "27017"
            - name: MONGODB_PASSWORD
              value: password
            - name: MONGODB_USER
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:5.0.8
          name: mongodb
          ports:
            - containerPort: 27017
              hostPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
status: {}
